let userLogin  = {"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzAxIiwidXNlciI6eyJuYW1lIjoiRElTVC4gQ0VOVFJFIC0xICIsInVzZXJuYW1lIjoiMTcwMSIsIm9wZXJhdG9yVHlwZSI6IlVzZXJCMkIiLCJwYXJraW5nU3ViTG90SWRzIjpbNDEsNDBdLCJwYXJraW5nTG90SWRzIjpbMTddLCJwYXJraW5nSWRzIjpbMTRdLCJjb21wYW55SWRzIjpbMV0sInVzZXJBY2Nlc3NlcyI6WyJBRE1JTl9NQU5BR0UiLCJBRE1JTl9SRVBPUlQiLCJDSEVDS0VEX0lOIiwiQ0hFQ0tFRF9PVVQiLCJGT0MiLCJQQVNTX0FERCIsIlBBU1NfREVMRVRFIiwiUEFTU19GUk9NX0RBVEUiLCJQQVNTX1VQREFURSIsIlJFUE9SVF9DT01QQU5ZIiwiUkVQT1JUX0dSQVBIIiwiUkVQT1JUX1BBU1MiLCJTUEVDSUFMX0FDQ0VTUyJdLCJhZmNNYXN0ZXJJZHMiOltdfSwiaXNzIjoiZ21wT3BlcmF0b3IiLCJleHAiOjE1MTI1NjM1NjV9.uYdhRv2_MFszc-qWmcW1cKpQ2G0Tts64WIhwkP8Xx5s",
    "operatorUser":{
        "name":"DIST. CENTRE -1 ",
        "username":"1701",
        "operatorType":"UserB2B",
        "parkingSubLotIds":[41,40],
        "parkingLotIds":[17],
        "parkingIds":[14],
        "companyIds":[1],
        "userAccesses":["ADMIN_MANAGE","ADMIN_REPORT","CHECKED_IN","CHECKED_OUT","FOC","PASS_ADD","PASS_DELETE","PASS_FROM_DATE","PASS_UPDATE","REPORT_COMPANY","REPORT_GRAPH","REPORT_PASS","SPECIAL_ACCESS"],
        "afcMasterIds":[]
    }
};
